name: superfluid
version: 0.1.0.0
github: "kontheocharis/superfluid"
license: MIT
author: "Constantine Theocharis"
maintainer: "cthe@mailbox.org"
copyright: "2024 Constantine Theocharis"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/rep-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.3 && < 2.4
  - parsec >= 3.1 && < 3.2
  - text >= 2.0 && < 2.1
  - haskeline >= 0.8 && < 0.9
  - optparse-applicative >= 0.18 && < 0.19
  - containers >= 0.6 && < 0.7
  - syb
  - extra >= 1.7 && < 1.8
  - array >= 0.5 && < 0.6
  - vector >= 0.13 && < 0.14
  - template-haskell >= 2.20 && < 2.21
  - criterion >= 1.6 && < 1.7
  - semirings >= 0.6 && < 0.7
  - random >= 1.2 && < 1.3
  - th-lift >= 0.8 && < 0.9
  - deepseq >= 1.4 && < 1.5
  - persistent-vector >= 0.2 && < 0.3
  - language-c >= 0.9 && < 0.10
  - language-javascript >= 0.7 && < 0.8
  - file-embed >= 0.0 && < 0.1
  - lattices >= 2.2 && < 2.3
  - singletons  >= 3.0 && < 3.1

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
  - LambdaCase
  - TupleSections
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors
  - PatternSynonyms
  - DeriveDataTypeable
  - DeriveTraversable
  - FlexibleInstances
  - MultiParamTypeClasses
  - TypeOperators

executables:
  superfluid-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O3
    dependencies:
      - superfluid

tests:
  superfluid-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - superfluid
