const prompt = require('prompt-sync')();
const Unit = null;
const tt = ["tt"];
const JS = null;
const to_js = (A) => (a) => a;
const js_null = null;
const js_undefined = undefined;
const js_true = true;
const js_false = false;
const js_zero = 0;
const js_one = 1;
const js_plus = (a) => (b) => (a) + (b);
const js_minus = (a) => (b) => (a) - (b);
const js_times = (a) => (b) => (a) * (b);
const js_div = (a) => (b) => (a) / (b);
const js_mod = (a) => (b) => (a) % (b);
const js_pow = (a) => (b) => (a) ** (b);
const js_neg = (a) => -(a);
const js_eq = (a) => (b) => (a) == (b);
const js_eqq = (a) => (b) => (a) === (b);
const js_neq = (a) => (b) => (a) != (b);
const js_neqq = (a) => (b) => (a) !== (b);
const js_lt = (a) => (b) => (a) < (b);
const js_lte = (a) => (b) => (a) <= (b);
const js_gt = (a) => (b) => (a) > (b);
const js_gte = (a) => (b) => (a) >= (b);
const js_and = (a) => (b) => (a) && (b);
const js_or = (a) => (b) => (a) || (b);
const js_not = (a) => !(a);
const js_if = (A) => (cond) => (t) => (f) => (cond) ? ((t)()) : ((f)());
const js_typeof = (a) => typeof (a);
const IO = null;
const js_console_log = (a) => (() => ((console).log)(a));
const js_prompt = (() => (prompt)());
const cast = (A) => (B) => (a) => a;
const io_return = (A) => (a) => (() => a);
const io_bind = (A) => (B) => (a) => (f) => (() => (f)(a));
const debug_print = (A) => (a) => (js_console_log)(((to_js)(A))(a));
const Maybe = (n65) => null;
const nothing = (A) => ["nothing", A];
const just = (A) => (n69) => ["just", A, n69];
const Equal = (A) => (n71) => (n72) => null;
const refl = (A) => (x) => ["refl", A, x];
const List = (n78) => null;
const nil = (A) => ["nil", A];
const cons = (A) => (n82) => (n83) => ["cons", A, n82, n83];
const Vec = (n84) => (n85) => null;
const vnil = (A) => ["vnil", A];
const vcons = (A) => (n) => (n91) => (n92) => ["vcons", A, n, n91, n92];
const Fin = (n94) => null;
const fz = (n) => ["fz", n];
const fs = (n) => (n98) => ["fs", n, n98];
const Char = (Fin)(((js_pow)(((js_plus)(js_one))(((js_plus)(js_one))(js_zero))))(((js_pow)(((js_plus)(js_one))(((js_plus)(js_one))(js_zero))))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(js_zero))))));
const String = (List)(Char);
const fib = (n) => ((((js_if)(null))(((js_eqq)(n))(js_zero)))((_) => (((cast)(null))(null))(js_zero)))((_) => (((cast)(null))(null))(((((js_if)(null))(((js_eqq)(((js_minus)(n))(js_one)))(js_zero)))((_) => (((cast)(null))(null))(((js_plus)(js_one))(js_zero))))((_) => (((cast)(null))(null))(((js_plus)((fib)(((js_minus)(n))(js_one))))((fib)(((js_minus)(((js_minus)(n))(js_one)))(js_one)))))));
const ten = ((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(((js_plus)(js_one))(js_zero))))))))));
const main = ((debug_print)(JS))((fib)(((js_times)(ten))(((js_plus)(js_one))(((js_plus)(js_one))(js_zero)))));
(main)()